---
- name: Ansible_ssh_conf_4_Ubuntu
  hosts: Ubuntu
  gather_facts: no
  
  tasks:
    - name: PermitRootLogin change from without-password to yes
      replace:
        dest: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin without-password'
        replace: 'PermitRootLogin yes'
        backup: yes
    - name: sshd restart to apply "PasswordAuthentication"
      service:
        name: sshd
        state: restarted
