---
- name: Install nginx on the nodes
  hosts: all
  become: yes
  vars:
    lnx_name: "{{ 'Ubuntu' if ansible_distribution == 'Ubuntu'
                   else 'CentOS' if ansible_distribution == 'CentOS'
                   else 'Just linux' }}"

  tasks:
  - name: nginx for any linux OS
    include_tasks: "{{lnx_name}}.yml"

  handlers:
  - name: Restart nginx web server
    service: name=nginx state=restarted
