---
- name: Install nginx on the All nodes
  hosts: CentOS, Ubuntu
  become: yes

  tasks:
    - name: Install nginx web server
      action : "{{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes"
      when : ansible_distribution == 'Ubuntu'
